### ISSUE TITLE
Api to register new packages

### ISSUE THREAD

**Issue by FraMecca** [dlang/dub-registry#259]
Hi,
with the desire to organize the D language libraries I knew I created this [repo](https://github.com/FraMecca/D_Libraries_Registry).

I'd like to import some of these packages into the DUB registry.
Is there some sort of automated API to add a package?

**Comment by s-ludwig** [comment]
Unless you intend to continuously maintain those packages, such as making sure that proper version tags are created and possible error messages are addressed, I'd recommend persuading the library owner instead to register it. I have made rather bad experiences trying to maintain the DUB package separately from the repository in the past.

For this reason, I'd also say that an API for automating package registration doesn't really make much sense. But in general it would certainly be possible to use the normal registration form together with a session cookie borrowed from a previously established browser session (`POST https://code.dlang.org/register_package?kind=github&owner=...&project=...`).

BTW, there is an effort going on to automatically make high-quality packages visible (see the "rating" column here: <https://code.dlang.org/?showrating>), so maybe it makes sense to somehow contribute there instead of investing in a more manual process.

Unrelated, but I noticed that there are is a number of vibe.d related projects on your list, it probably makes sense to mention [vibe.d](https://vibed.org/) itself, too.
