### ISSUE TITLE
Search from dub.pm attempts to search `127.0.0.1:8005`

### ISSUE THREAD

**Issue by andrewbenton** [dlang/dub-registry#320]
When attempting to use the search bar from dub.pm instead of code.dlang.org, the search fails because it's attempting to contact http://127.0.0.1:8005 instead of https://dub.pm.

Steps to reproduce:
1. go to https://dub.pm
2. search for `protobuf`
3. search is directed to http://127.0.0.1:8005/search?q=protobuf and fails

This doesn't fail if you go to https://code.dlang.org instead in the first step.

**Comment by wilzbach** [comment]
Yeah, because dub.pm is _not_ the registry - it's just a local dump that we use for previewing things and eventually for displaying sun's documentation. I will take it offline or revert to the redirect though until this transition is fully done as I agree that it might be confusing because it looks so real ;-)

**Comment by wilzbach** [comment]
Redirect is in place again.

**Comment by wilzbach** [comment]
(sorry for the confusion caused)
