### ISSUE TITLE
why do new versions of dub never show up when you click download on the dub page.

### ISSUE THREAD

**Issue by sxkladi** [dlang/dub-registry#403]
why do new versions of dub never show up when you click download on the dub page.
this seems to happen all of the time now.
Since before 1.11.0

**Comment by ZombineDev** [comment]
The download page was created and actively used when the releases were done manually and back then it was the source of truth. Since then, we moved to building new releases of dub automatically via CI/CD when a commit is tagged and uploading them to the GitHub release page, which has since then become the new source of truth.

The other important development is that dub is included in every compiler release, so for most people at least, there should be no need to download dub manually.

**Comment by ZombineDev** [comment]
The only actionable item here is to either remove the download section entirely and link to the GitHub releases page, or to generate the release page based on GitHub API. Though I'm sure if the latter is worth it.

**Comment by wilzbach** [comment]
We'll go with replacing the download section with a redirect: https://github.com/dlang/dub-registry/pull/401

**Comment by ZombineDev** [comment]
@sxkladi Feel free to reopen this issue if you have further questions or suggestions.
