### ISSUE TITLE
Wrong rendering of markdown 

### ISSUE THREAD

**Issue by andre2007** [dlang/dub-registry#438]
Please have a look at this package.
http://code.dlang.org/packages/coding-puzzles?tab=info

The lower part of the documentation is rendered wrong compared to the Github rendering.

```
# Coding Puzzles

See [PUZZLES.md](PUZZLES.md) for list of available puzzles.

## Onboarding sample

Execute puzz init to create file puzzles/cg.easy.onboarding/d/app.d
```puzz init onboarding```

Edit app.d and execute puzz play to play the quest
```puzz play onboarding```
```

Looks like this

![image](https://user-images.githubusercontent.com/1451047/64493575-0c923280-d282-11e9-84ed-2df5fe6ddf46.png)

**Comment by s-ludwig** [comment]
```foo```

should result in `<code></code><code>foo</code></code>`, because the CommonMark spec dicates that no backticks may follow after the initial backtick sequence for a code fence marker, so that the above does not qualify as a fenced code block. Also, the same line does not qualify as a closing code fence, because no non-space characters may follow the backtick sequence for a closing marker. Currently none of these rules are enforced.

**Comment by s-ludwig** [comment]
It should of course be noted that the example should still be changed to either use only single backticks, or to put the triple-backtickes each on their own line, even if a CommonMark compliant parser produces a seemingly correct result.

**Comment by andre2007** [comment]
Thanks I will correct it. 

I just had a look at https://spec.commonmark.org/dingus/. Although this tool renders the "wrong" markdown correctly.
