### ISSUE TITLE
Bring back good-old copy&paste dependency boxes

### ISSUE THREAD

**Issue by 0xEAB** [dlang/dub-registry#442]
The way #391 forces you to use to add new dependencies blows up all formatting and structuring of your `dub.[json|sdl]`. This is definitely not acceptable for quite a few projects/use-cases.

I wonder why such changes always have to be applied in a black/white-only way. Why can't there be **both** options? What would be the problem with having all of them: the fresh *`dub add` box* and the good old *copy&paste boxes*?

(This issue is *not* a duplicate of #439 because #439 aims at improving `dub add` and/or the *`dub add` box* instead.)

**Comment by 0xEAB** [comment]
UPDATE: This is actually **pretty annoying**. You might not believe it, but distros out there package older versions of DUB where `dub add` isn't a thing yet. (There you'll find yourself doing all this busywork of trying to figure out which version to specify plus how that syntax was.)

**Comment by PetarKirov** [comment]
> Why can't there be both options? What would be the problem with having all of them: the fresh dub add box and the good old copy&paste boxes?

I agree that having both options is a good idea. Additionally we need to fix `dub add` rewrite `dub.{sdl,json}` files from scratch, but instead just modifies the dependencies section in a smarter way.


> You might not believe it, but distros out there package older versions of DUB where dub add isn't a thing yet.

`<rant>`
Supporting the D toolchain (or any other language for that matter) in a non-rolling distro is a non-starter in my opinion. Due to the release cadence of distros like Debian or Ubuntu, all language toolchains are always outdated. This may not be an issue with C, where new versions are released not less than 10 years apart, so it's unlikely that you're going to miss any feature, but D the toolchain has a major release every two months.
To add insult to the injury, typically distro package managers have their own way of building packages (not using the upstream release scripts), so it's hard to know exactly what is being packaged.
Say we need to rearchitect the API of the dub registry. When users use rolling distros, or even better - manage their toolchains themselves, we can ask everyone to upgrade and wait a couple of releases, before enabling the new API endpoints and shutting down the old ones. But now with non-rolling distros in the picture, who knows how many years we would need if we want to make breaking changes to the API registry?
`</rant>`

**Comment by Geod24** [comment]
> who knows how many years we would need if we want to make breaking changes to the API registry?

My turn to `<rant>`.
As painful as it is, it is also the way many companies work. Breaking stuff is simply pushing your problems onto someone else. There's no point in writing a library in a language that might not be usable in 2 years time. As a corporate user, I don't want to have to adapt my agenda to your random language change, nor should you expect me to, period.

We as a community are always way too eager to break other people's code. "This code shouldn't compile" or "It's misleading" or "That code is broken anyway" are sentence way too annoyingly common. I wish we put more care into what we break, and when we break it.
`</rant>`

PS: Maybe we can continue this on Slack :D

**Comment by 0xEAB** [comment]
> Supporting the D toolchain (or any other language for that matter) in a non-rolling distro is a non-starter in my opinion.

Do you understand that you're ranting about something that no one did ask for in the first place? (Apart from that, many non-rolling distros provide new major version every 2 years or even more often – which I'd claim isn't that long.)

By the way, you did your great job already – DUB doesn't work anymore on the latest Raspbian (Debian 10) on my RPi (which does not provide sufficient memory to manually compile a newer version):
```
Package asdf not found in registry at https://code.dlang.org/ (fallback ["registry at http://code.dlang.org/", "registry at https://code-mirror.dlang.io/", "registry at https://code-mirror2.dlang.io/", "registry at https://dub-registry.herokuapp.com/"]): HTTP request returned status code 503 (Service Unavailable)
```

But I'm not here to complain about that :)

I just would like to remind you that the change introduced to the DUB registry did break stuff for no reason – reducing usability for everyone in order to push some new shiny feature. That's all I'm criticizing.

inb4: I know that indeed many people did ask for `dub add` (but I'm not sure whether any of them did ask for removing the old boxes…)

**Comment by wilzbach** [comment]
> I just would like to remind you that the change introduced to the DUB registry did break stuff for no reason – reducing usability for everyone in order to push some new shiny feature. That's all I'm criticizing.

And I would like to remind you that this is an open source project ;-)
No one gets paid here.
If you're annoyed by this, the best way to fix it is to submit a PR for it.

**Comment by 0xEAB** [comment]
Will do so as soon as I find time for it :)

It's just that this issue did not receive any replies until a few days ago. (And as this is adding back a feature that got presumably intentionally removed, I would have preferred to get some feedback first – that I got now –, instead of going for a PR straightaway.)

**Comment by 0xEAB** [comment]
It's there :)
