### ISSUE TITLE
Manual update does not work

### ISSUE THREAD

**Issue by matti-82** [dlang/dub-registry#495]
I triggered a manual update for the package easyd, but it is never performed. I see the status message "Still have to wait for 1683 other packages to complete". And when the countdown goes down to ~1000, it jumps up to ~1700 again.

**Comment by s-ludwig** [comment]
Could it be that it has actually performed the update, but was too quick to notice? I just tried and it definitely worked, but it was quite quick due to the fact that the package that was already updating at that moment only had few versions.

It might make sense to add a "last updated" date to each package, so that this becomes clearer.

**Comment by matti-82** [comment]
0.9.0 is still shown, although 0.13.0 is the current version on github

**Comment by matti-82** [comment]
Found the problem, the tags have not been pushed.
