### ISSUE TITLE
Registry accepts packages with no description

### ISSUE THREAD

**Issue by 0xEAB** [dlang/dub-registry#526]
[Spec says](https://dub.pm/package-format-json)
> description [required for publishing]

yet the registry still allows them:
- https://code.dlang.org/packages/uim-vue

which breaks downstream services/tools:
> The project build failed. […]
> `arsd.database.DatabaseException@/home/me/program/lib/arsd/postgres.d(134):` ERROR:  null value in column "description" violates not-null constraint
DETAIL:  Failing row contains `(2271, uim-vue, uim-vue, null, , null)`.

**Comment by WebFreak001** [comment]
it seems there was a description before: https://github.com/UI-Manufaktur/uim-vue/commit/39381144ec3f700054cd19416f529b5d61ba8d42#diff-1b617af56e869773e32ce59329f25b2db5d8b3c5151519919c7c10266b4d78fcR4

however the repository owner deleted it later. I think there is nothing we can do on our side, a warning will be shown to the package author when releasing new versions with this, but otherwise we can't really control what happens on the github repository.

The tools should probably be adjusted to allow for this kind of behavior.

**Comment by 0xEAB** [comment]
This could probably be stated in the docs/"spec".
