### ISSUE TITLE
Transfer ownership of bindbc-imgui

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [dlang/dub-registry#541]
For a while the Inochi2D team has been maintaining a package called bindbc-imgui, though the bindbc developers intend to make an official package, as such it'd be a good idea to transfer ownership of bindbc-imgui to `ichordev` from me.
Will then rename our repo and release new versions as `i2d-imgui`

**Comment by WebFreak001** [comment]
I see you own the bindbc-imgui package, do you want to change its package name?

Changing repository/owner is something you can do on your own in the settings, but not renaming the package name on DUB.

Since we don't want to break existing users and if the bindbc developers intend to make an official package, it might make more sense to let the bindbc devs start as a fork of your package. You could then change the repo location on DUB to the fork and re-register the original repo under a new name. When that's done we can also change the DUB user ownership of the package on the registry.

**Comment by ichordev** [comment]
Here to confirm about the transfer.

> Since we don't want to break existing users and if the bindbc developers intend to make an official package, it might make more sense to let the bindbc devs start as a fork of your package. You could then change the repo location on DUB to the fork and re-register the original repo under a new name. When that's done we can also change the DUB user ownership of the package on the registry.

Yep my plan is to do that basically: https://github.com/Inochi2D/bindbc-imgui/issues/24
Also no need for the plurals, there's only one of me. :)

> Changing repository/owner is something you can do on your own in the settings, but not renaming the package name on DUB.

Really, how? I only know about this text.
<img width="567" alt="Screenshot 2023-03-19 at 07 22 34" src="https://user-images.githubusercontent.com/15670465/226140777-279e4fc9-41a1-49d0-b294-2969d2e3078c.png">

**Comment by WebFreak001** [comment]
yes, under the repository tab you can configure which GitHub / other repository is used to fetch releases and source code from. If you fork Inoch2D/bindbc-imgui to your BindBC org, Luna or dub admins can then change the repository location in the package settings. (the migrate screenshot you posted)

So that would bascially mean:

1. Fork Inochi2D/bindbc-imgui to YourBindBCOrg/bindbc-imgui (something IchorDev can do)
2. DUB package bindbc-imgui: repository Inochi2D/bindbc-imgui -> YourBindBCOrg/bindbc-imgui (something Luna or dub admins can do)
3. now Inochi2D/bindbc-imgui can freely rename and change the package name in the dub.json/dub.sdl file and later reregister on DUB under Inochi2D/i2d-imgui (something Luna can do)

Afterwards we can also transfer the package owner on dub, so you (IchorDev) are admin of the package, instead of Luna, so you can also trigger new releases, change image, etc. (This is something only s-ludwig can do though, I think, as it needs database access right now)

**Comment by ichordev** [comment]
Yep, here it is: https://github.com/BindBC/bindbc-imgui


also oops I screenshot the wrong text, but basically I thought you were saying you could transfer package ownership through the web interface.

**Comment by ichordev** [comment]
Any updates on this? The new BindBC-ImGui is basically ready for an alpha-release.

**Comment by WebFreak001** [comment]
ok dub package points to BindBC/bindbc-imgui now. Should the dub account ownership also be transferred somewhere or stay with @LunaTheFoxgirl's account?

@LunaTheFoxgirl you can also rename your package in dub.json/dub.sdl and re-register it. Note that you will need to rewrite git history if you want previous versions to work as well (otherwise only new versions with the new package name will properly function)

**Comment by ichordev** [comment]
It’s probably simplest to transfer the existing package and then wait for the Inochi2D team register a new one. I’m just about ready to release the new BindBC-ImGui version, but I want to be able to mention where the other bindings have moved to when I do.

**Comment by ichordev** [comment]
> the package is already transferred, when you make new releases they will appear on dub. What's your username on dub so we can also give you access to the package admin interface that can be used for manual release triggers?

`ichordev` :)

**Comment by WebFreak001** [comment]
@s-ludwig can you do the package ownership migration?

**Comment by s-ludwig** [comment]
Done!
